apiVersion: apps/v1
kind: Deployment
metadata:
  name: koa-app
  labels:
    app: koa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koa-app
  template:
    metadata:
      labels:
        app: koa-app
    spec:
      containers:
        - name: koa-container
          image: koa-app:1.0.1 # 替换为你的 Koa 应用镜像
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: koa-app
  labels:
    app: koa-app
spec:
  selector:
    app: koa-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: koa-app-gateway
spec:
  selector:
    istio: ingressgateway # 使用 Istio 的 Ingress Gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: koa-app
spec:
  hosts:
  - "*"
  gateways:
  - koa-app-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: koa-app
        port:
          number: 3000